/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#FFFBEA",
          100: "#FFF3C4",
          200: "#FFE680",
          400: "#F9C01E",
          600: "#D4A017",
          800: "#9A7010",
        },
        dark: {
          50: "#F7F7F5",
          100: "#EEEEEA",
          300: "#BBBBBA",
          500: "#888886",
          700: "#444442",
          900: "#1A1A1A",
        },
        surface: "#FFFFFF",
        background: "#FAFAF5",
        success: "#4CAF7D",
        error: "#E84040",
        info: "#4A90D9",
        "missed-bg": "#FFF0F0",
        "missed-border": "#FFBCBC",
      },
      fontFamily: {
        jakarta: ["PlusJakartaSans-Regular"],
        "jakarta-medium": ["PlusJakartaSans-Medium"],
        "jakarta-semibold": ["PlusJakartaSans-SemiBold"],
        "jakarta-bold": ["PlusJakartaSans-Bold"],
        "jakarta-extrabold": ["PlusJakartaSans-ExtraBold"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", fontWeight: "800" }],
        h1: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        h4: ["17px", { lineHeight: "1.5", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        body: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        label: ["13px", { lineHeight: "1.5", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      borderRadius: {
        chip: "8px",
        input: "12px",
        card: "16px",
        "card-lg": "20px",
        modal: "24px",
        pill: "9999px",
      },
      boxShadow: {
        lifted: "0 2px 8px rgba(0,0,0,0.06)",
        raised: "0 4px 16px rgba(0,0,0,0.10)",
        floating: "0 8px 32px rgba(0,0,0,0.14)",
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
      },
    },
  },
  plugins: [],
};
